server:
  port: 8080
spring:
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      default_schema: public
      ddl-auto: update
      globally_quoted_identifiers: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true

zego:
  app-id: "${ZEGO_APP_ID}"
  server-secret: "${ZEGO_SERVER_SECRET}"

aws:
  accessKeyId: "${AWS_ACCESS_KEY_ID}"
  secretKey: "${AWS_SECRET_ACCESS_KEY}"
  s3.bucket: "${AWS_S3_BUCKET}"
  region: "${AWS_REGION}"

logging:
  level:
    org.springframework.security: DEBUG
